### ISSUE TITLE
please provide download link for file Doku.php

### ISSUE THREAD

**Issue by erlangparasu** [PTNUSASATUINTIARTHA-DOKU/SDK-Android#2]

**Comment by ariefrizkyr** [comment]
Hi there, we are sorry for the inconvenience. The link on our documentation must be broken. Here is the file:

[Dokuphp.zip](https://github.com/PTNUSASATUINTIARTHA-DOKU/SDK-Android/files/5480442/Dokuphp.zip)

**Comment by erlangparasu** [comment]
thank you very much sir :D
