### ISSUE TITLE
5504 WORDS_DOES_NOT_MATCH

### ISSUE THREAD

**Issue by erlangparasu** [PTNUSASATUINTIARTHA-DOKU/SDK-Android#3]
{
    "res_response_msg": "WORDS_DOES_NOT_MATCH",
    "res_response_code": "5504"
  }

**Comment by erlangparasu** [comment]
padahal saya sudah generate sha1 dan cocok, tetap dapat error 5504

**Comment by ariefrizkyr** [comment]
Hi @erlangp , we are sorry for the inconvenience. Can you please share the request parameter and the words component to our email productpayment@doku.com, so that we can trace it. Thank you!

**Comment by erlangparasu** [comment]
solved. doku team give me new sharedkey and works. the issue gone.
